[[mybatis-init-mapping]]
== 解析 Mapper 接口与 XML 映射文件
首先，在 `MybatisPlusAutoConfiguration` 自动配置类中，Spring Boot 通过 `MybatisSqlSessionFactoryBean` 来构建  `SqlSessionFactory` 实例,让我们先从 `MybatisSqlSessionFactoryBean` 类的 `buildSqlSessionFactory()` 方法来看看如何完成 XML 文件解析。

[source,java]
.MybatisSqlSessionFactoryBean
----
public class MybatisSqlSessionFactoryBean implements FactoryBean<SqlSessionFactory>, InitializingBean, ApplicationListener<ApplicationEvent> {
    //... 省略部分代码
	protected SqlSessionFactory buildSqlSessionFactory() throws Exception {
        //... 省略部分代码
        // 判断是否具有 mapper xml 文件
        if (this.mapperLocations != null) {
            if (this.mapperLocations.length == 0) {
                LOGGER.warn(() -> "Property 'mapperLocations' was specified but matching resources are not found.");
            } else {
                // 对每一个 mapper 文件进行解析
                for (Resource mapperLocation : this.mapperLocations) {
                    if (mapperLocation == null) {
                        continue;
                    }
                    try {
                        // 使用 XMLMapperBuilder 对象进行解析构建
                        XMLMapperBuilder xmlMapperBuilder = new XMLMapperBuilder(mapperLocation.getInputStream(),
                            targetConfiguration, mapperLocation.toString(), targetConfiguration.getSqlFragments());
                        xmlMapperBuilder.parse();
                    } catch (Exception e) {
                        throw new NestedIOException("Failed to parse mapping resource: '" + mapperLocation + "'", e);
                    } finally {
                        ErrorContext.instance().reset();
                    }
                    LOGGER.debug(() -> "Parsed mapper file: '" + mapperLocation + "'");
                }
            }
        } else {
            LOGGER.debug(() -> "Property 'mapperLocations' was not specified.");
        }
        //... 省略部分代码
    }
	//... 省略部分代码
}


----

首先，MybatisPlus 会检查是否具有 mapper 文件，如果存在，并且 mapper 文件数量大于 0，MybatisPlus 循环读取 mapper 文件，并为每一个文件创建一个 Mybatis 的 `XMLMapperBuilder` 对象，该对象包含了 `mapper.xml` 文件流，全路径文件名，Configuration 对象，以及当前对象的 sqlFragments（即 sql 片段）。
至此，进入到 Mybatis 源码环节，使用 XMLMapperBuilder 对象的 `parse` 方法进行解析。我们来深入 `parse` 方法。

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
    //... 省略部分代码
    public void parse() {
        // 判断资源是否已经加载过，加载过则不进行处理
        if (!configuration.isResourceLoaded(resource)) {
          configurationElement(parser.evalNode("/mapper"));
          // 将此资源标记为已加载
          configuration.addLoadedResource(resource);
          // 绑定 mapper 对象和 mapper 命名空间
          bindMapperForNamespace();
        }

        // 解析未完成的结果集
        parsePendingResultMaps();
        // 解析未完成的缓存
        parsePendingCacheRefs();
        // 解析未完成的 SQL 语句
        parsePendingStatements();
    }

	private void configurationElement(XNode context) {
        try {
            // 获取命名空间，可见 mapper 文件的命名空间不能为空，也不能为空字符串。我们这里的为: com.mybatis.sql.mapper.UserMapper
          String namespace = context.getStringAttribute("namespace");
          if (namespace == null || namespace.isEmpty()) {
            throw new BuilderException("Mapper's namespace cannot be empty");
          }
          // 设置当前的命名空间
          builderAssistant.setCurrentNamespace(namespace);
          // 解析 cache-ref 相关配置
          cacheRefElement(context.evalNode("cache-ref"));
          // 解析 cache 相关配置
          cacheElement(context.evalNode("cache"));
          // 解析 mapper 标签下的  parameterMap 相关配置，参数配置
          parameterMapElement(context.evalNodes("/mapper/parameterMap"));
          // 解析 mapper 标签下的 resultMap 相关配置，解析完成后放入到 configuration 的 resultMaps 属性。key 是由我们当前 mapper 文件的命名空间和标签定义里的 id 拼接而来的。这样不同的命名空间就可以只用相同的id定义，由此命名空间起到了隔离的作用。
          resultMapElements(context.evalNodes("/mapper/resultMap"));
          // 解析 sql 标签 放入到  configuration   的属性 sqlFragments 参数里，sql 片段信息
          sqlElement(context.evalNodes("/mapper/sql"));
          // 这个方法是我们解析 SQL 语句的关键地方，这里包含一些我们的if 等标签的解析。解析完成后存放在
          buildStatementFromContext(context.evalNodes("select|insert|update|delete"));
        } catch (Exception e) {
          throw new BuilderException("Error parsing Mapper XML. The XML location is '" + resource + "'. Cause: " + e, e);
        }
    }

    //... 省略部分代码

}

----

[source,java]
.XNode
----
public class XNode {
    //... 省略部分代码
	public XNode evalNode(String expression) {
        return xpathParser.evalNode(node, expression);
    }
	//... 省略部分代码
}
----

[source,java]
.XPathParser
----
public class XPathParser {
	//... 省略部分代码
	public XNode evalNode(Object root, String expression) {
        Node node = (Node) evaluate(expression, root, XPathConstants.NODE);
        if (node == null) {
            return null;
        }
        return new XNode(this, node, variables);
    }
	//... 省略部分代码
}

----

Mybatis 3.5 中将 xml 文件解析为 `XNode` 对象的方法是通过 `XMLParser` 进行解析。`XMLParser` 是 Mybatis 提供的一个用于解析 xml 文件的工具类，可以读取 xml 文件，并将其转换为 `XNode` 对象。解析过程不做过多说明，我们现在只需要关心 `XNODE` 节点信息即可。

通过以上源码可知，`configurationElement(parser.evalNode("/mapper"))` 这个方法就是解析整个 mapper 文件的入口，主要包含以下属性：

* cache-ref：该命名空间引用其他命名空间的缓存配置
* cache：该命名空间的缓存配置
* parameterMap：参数映射
* resultMap：描述如何从数据库结果集中加载对象
* sql：可被其他语句引用的可重用语句块，SQL 片段
* select：映射查询语句
* insert：映射插入语句
* update：映射更新语句
* delete：映射删除语句

下面我们进入到这些方法中看看发生了什么？

=== cacheRefElement 方法

`cacheRefElement(XNode context)` 方法用于解析XML映射文件中的 `<cache-ref />` 节点，代码如下：

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
    //... 省略部分代码
    private void cacheRefElement(XNode context) {
        if (context != null) {
            // <1> 获得指向的 namespace 名字，并添加到 configuration 的 cacheRefMap 中
            configuration.addCacheRef(builderAssistant.getCurrentNamespace(), context.getStringAttribute("namespace"));
            // <2> 创建 CacheRefResolver 对象
            CacheRefResolver cacheRefResolver = new CacheRefResolver(builderAssistant, context.getStringAttribute("namespace"));
            try {
                // 执行解析，获取引用的缓存对象到自己这里
                cacheRefResolver.resolveCacheRef();
            } catch (IncompleteElementException e) {
                configuration.addIncompleteCacheRef(cacheRefResolver);
            }
        }
    }
    //... 省略部分代码
}
----

解析当前 XML 映射文件的缓存配置，将当前 namespace 缓存引用其他的 namespace 的缓存形成映射关系保存在 Configuration 全局配置对象中

获取引用的 namespace 的缓存实例，将其设置到 `MapperBuilderAssistant` 构造器助手中，在后续构建相关对象时使用

=== cacheElement 方法

`cacheElement(XNode context)` 方法用于 XML 映射文件中的 `<cache />` 节点，代码如下：

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
	//... 省略部分代码
    private void cacheElement(XNode context) {
        if (context != null) {
            // <1> 获得负责存储的 Cache 实现类
            String type = context.getStringAttribute("type", "PERPETUAL");
            Class<? extends Cache> typeClass = typeAliasRegistry.resolveAlias(type);
            // <2> 获得负责过期的 Cache 实现类
            String eviction = context.getStringAttribute("eviction", "LRU");
            Class<? extends Cache> evictionClass = typeAliasRegistry.resolveAlias(eviction);
            // <3> 获得 flushInterval、size、readWrite、blocking 属性
            Long flushInterval = context.getLongAttribute("flushInterval");
            Integer size = context.getIntAttribute("size");
            boolean readWrite = !context.getBooleanAttribute("readOnly", false);
            boolean blocking = context.getBooleanAttribute("blocking", false);
            // <4> 获得 Properties 属性
            Properties props = context.getChildrenAsProperties();
            // <5> 创建 Cache 对象
            builderAssistant.useNewCache(typeClass, evictionClass, flushInterval, size, readWrite, blocking, props);
        }
    }
	//... 省略部分代码
}
----

解析该节点的相关配置，然后通过 `MapperBuilderAssistant` 构造器小助手创建一个 `Cache` 缓存实例，添加到 Configuration 全局配置对象中，并设置到构造器助手中，在后续构建相关对象时使用

=== parameterMapElement 方法

`parameterMapElement(List<XNode> list)` 方法主要用来解析 `<parameterMap />` 其代码如下：

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
    //... 省略部分代码
    private void parameterMapElement(List<XNode> list) {
        for (XNode parameterMapNode : list) {
			// 获取 id 和 type 类型
            String id = parameterMapNode.getStringAttribute("id");
            String type = parameterMapNode.getStringAttribute("type");
			// 获取 type 对象的 clazz 对象
            Class<?> parameterClass = resolveClass(type);
			// 获取所有的 parameter 节点
            List<XNode> parameterNodes = parameterMapNode.evalNodes("parameter");
            List<ParameterMapping> parameterMappings = new ArrayList<>();
            for (XNode parameterNode : parameterNodes) {
				// 获取节点属性
                String property = parameterNode.getStringAttribute("property");
                String javaType = parameterNode.getStringAttribute("javaType");
                String jdbcType = parameterNode.getStringAttribute("jdbcType");
                String resultMap = parameterNode.getStringAttribute("resultMap");
                String mode = parameterNode.getStringAttribute("mode");
                String typeHandler = parameterNode.getStringAttribute("typeHandler");
                Integer numericScale = parameterNode.getIntAttribute("numericScale");
				// 获取参数模型，输入，输出，输入输出
                ParameterMode modeEnum = resolveParameterMode(mode);
                Class<?> javaTypeClass = resolveClass(javaType);
                JdbcType jdbcTypeEnum = resolveJdbcType(jdbcType);
                Class<? extends TypeHandler<?>> typeHandlerClass = resolveClass(typeHandler);
				//
				ParameterMapping parameterMapping = builderAssistant.buildParameterMapping(parameterClass, property, javaTypeClass, jdbcTypeEnum, resultMap, modeEnum, typeHandlerClass, numericScale);
                parameterMappings.add(parameterMapping);
            }
			// 构建 ParameterMap 对象
            builderAssistant.addParameterMap(id, parameterClass, parameterMappings);
        }
    }
    //... 省略部分代码
}
----

. 获取  `<parameterMap />` 节点的 `id` 和 `type` 属性，并获取 type 所对应的 clazz 对象
. 获取所有的 `<parameter />` 节点，进行逐个解析，获取他的所有节点信息。
. 通过 `MapperBuilderAssistant.buildParameterMapping()` 方法获取到一个 `ParameterMapping` 对象。并添加到 `parameterMappings` 集合中。
. 通过 `MapperBuilderAssistant.addParameterMap` 方法构建 `ParameterMap` 对象并添加到 Configuration 全局配置中

[source,java]
.MapperBuilderAssistant
----
public class MapperBuilderAssistant extends BaseBuilder {
	public ParameterMap addParameterMap(String id, Class<?> parameterClass, List<ParameterMapping> parameterMappings) {
        id = applyCurrentNamespace(id, false);
        ParameterMap parameterMap = new ParameterMap.Builder(configuration, id, parameterClass, parameterMappings).build();
        configuration.addParameterMap(parameterMap);
    return parameterMap;
    }
}
----

. 获取 id
. 通过 `ParameterMap.Builder` 构建一个 `ParameterMap` 对象，并添加到 Configuration 全局配置中

=== resultMapElements 方法

`resultMapElements(List<XNode> list)` 方法用于解析 `<resultMap />` 节点，最后会调用 `resultMapElement(XNode resultMapNode, List<ResultMapping> additionalResultMappings, Class<?> enclosingType)` 方法逐个解析生成 `ResultMap` 对象，关于 `resultMapElement` 方法参数说明：

* resultMapElement：当前节点信息
* additionalResultMappings：继承的 ResultMap 所对应的 ResultMapping 的集合，可以通过 extend 属性配置继承哪个 ResultMap，没有继承的话就是空集合
* enclosingType：所属的 ResultMap 的类型，例如 `<resultMap />` 中的 `<association />` 也会被解析成 ResultMap，那么它的 enclosingType 就是所属 ResultMap 的 Class 对象

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
	//... 省略部分代码
    /**
    * resultMapNode: 当前节点信息
    * additionalResultMappings：继承的 ResultMap 所对应的 ResultMapping 的集合，可以通过 extend 属性配置继承哪个 ResultMap，没有继承的话就是空集合
    * enclosingType：所属的 ResultMap 的类型，例如 <resultMap /> 中的 <association /> 也会被解析成 ResultMap，那么它的 enclosingType 就是所属 ResultMap 的 Class 对象
    */
    private ResultMap resultMapElement(XNode resultMapNode, List<ResultMapping> additionalResultMappings, Class<?> enclosingType) throws Exception {
        // 获取当前线程的上下文
        ErrorContext.instance().activity("processing " + resultMapNode.getValueBasedIdentifier());
        // <1> 获得 type 属性, 也既 resultMap 映射的类 javaType、resultType、ofType、type 优先级顺序是 type > ofType > resultType >javaType。
        String type = resultMapNode.getStringAttribute("type", resultMapNode.getStringAttribute("ofType",
                resultMapNode.getStringAttribute("resultType", resultMapNode.getStringAttribute("javaType"))));
        // 从别名注册表中获得 type 对应的类
        Class<?> typeClass = resolveClass(type);
        if (typeClass == null) {
            // 从 enclosingType Class 对象获取该 property 属性的 Class 对象
            typeClass = inheritEnclosingType(resultMapNode, enclosingType);
        }
        Discriminator discriminator = null;
        // 创建 ResultMapping 集合
        List<ResultMapping> resultMappings = new ArrayList<>();
        // 添加父 ResultMap 的 ResultMapping 集合
        resultMappings.addAll(additionalResultMappings);
        // <2> 遍历 <resultMap /> 的子节点
        List<XNode> resultChildren = resultMapNode.getChildren();
        for (XNode resultChild : resultChildren) {
            if ("constructor".equals(resultChild.getName())) {
                // <2.a> 处理 <constructor /> 节点
                processConstructorElement(resultChild, typeClass, resultMappings);
            } else if ("discriminator".equals(resultChild.getName())) {
                // <2.b> 处理 <discriminator /> 节点
                discriminator = processDiscriminatorElement(resultChild, typeClass, resultMappings);
            } else {
                // <2.c> 处理其它节点
                List<ResultFlag> flags = new ArrayList<>();
                if ("id".equals(resultChild.getName())) {
                  // 为添加该 ResultMapping 添加一个 Id 标志
                    flags.add(ResultFlag.ID);
                }
                // 生成对应的 ResultMapping 对象
                resultMappings.add(buildResultMappingFromContext(resultChild, typeClass, flags));
            }
        }
        // 获得 id 属性，没有的话自动生成
        String id = resultMapNode.getStringAttribute("id", resultMapNode.getValueBasedIdentifier());
        // 获得 extends 属性
        String extend = resultMapNode.getStringAttribute("extends");
        // 获得 autoMapping 属性
        Boolean autoMapping = resultMapNode.getBooleanAttribute("autoMapping");
        // <3> 创建 ResultMapResolver 对象，执行解析
        ResultMapResolver resultMapResolver = new ResultMapResolver(builderAssistant, id, typeClass, extend,
                discriminator, resultMappings, autoMapping);
        try {
          // 处理 ResultMap 并添加到 Configuration 全局配置中
            return resultMapResolver.resolve();
        } catch (IncompleteElementException e) {
            configuration.addIncompleteResultMap(resultMapResolver);
            throw e;
        }
    }
    //... 省略部分代码
}
----

. 获得 type 属性，生成该 ResultMap 对应 Class 对象，如果没有定义 type 属性，则可能是 `<association />` 标签，尝试从所属 ResultMap 的 Class 对象获取 property 的 Class 对象，因为 `<resultMap />` 标签中配置的 `<association />` 标签也会解析成一个 `ResultMap` 对象
. 遍历 `<resultMap />` 的子节点，依次处理
.. 如果是 `<constructor />` 节点，则调用 `processConstructorElement` 方法进行解析，再获取它的子节点生成对应的 `RequestMapping` 对象，这些 `RequestMapping` 对象会添加 `ResultFlag.CONSTRUCTOR` 标记，如果是 `<idArg />` 标签则再添加一个 `ResultFlag.ID` 标记，这些对象会在实例化类时，注入到构造方法中
.. 如果是 `<discriminator>` 节点，则调用 `processDiscriminatorElement` 方法进行解析，创建一个 `Discriminator` 选择器对象，用于可以使用结果值来决定这个属性使用哪个 ResultMap，基于 `<case />` 子节点来进行映射
.. 其他节点，则调用 `buildResultMappingFromContext` 方法进行解析，如果是 `<id />` 则添加一个 `ResultFlag.ID` 标记，生成对应的 `RequestMapping` 对象
. 创建 `ResultMapResolver` 对象，调用其 `resolve()` 方法执行解析，内部调用 `MapperBuilderAssistant` 构造器小助手的 `addResultMap` 来生成 `ResultMap` 对象

上面的 2.a 和 2.b 并不复杂，感兴趣的小伙伴可以查看相关方法，都已经注释好了，我们来看下 2.c 是如何解析成 ResultMapping 对象的

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
	//... 省略部分代码
    private ResultMapping buildResultMappingFromContext(XNode context, Class<?> resultType, List<ResultFlag> flags) {
        String property;
        // 如果是构造方法节点
        if (flags.contains(ResultFlag.CONSTRUCTOR)) {
          property = context.getStringAttribute("name");
        } else {
          property = context.getStringAttribute("property");
        }
        String column = context.getStringAttribute("column");
        String javaType = context.getStringAttribute("javaType");
        String jdbcType = context.getStringAttribute("jdbcType");
        String nestedSelect = context.getStringAttribute("select");
        // 解析 <resultMap /> 标签中的 <association />，<collection />，<case /> 标签，生成 ResultMap 对象
        String nestedResultMap = context.getStringAttribute("resultMap", () ->
            processNestedResultMappings(context, Collections.emptyList(), resultType));
        String notNullColumn = context.getStringAttribute("notNullColumn");
        String columnPrefix = context.getStringAttribute("columnPrefix");
        String typeHandler = context.getStringAttribute("typeHandler");
        String resultSet = context.getStringAttribute("resultSet");
        String foreignColumn = context.getStringAttribute("foreignColumn");
        boolean lazy = "lazy".equals(context.getStringAttribute("fetchType", configuration.isLazyLoadingEnabled() ? "lazy" : "eager"));
        // javaType 属性
        Class<?> javaTypeClass = resolveClass(javaType);
        // typeHandler 属性
        Class<? extends TypeHandler<?>> typeHandlerClass = resolveClass(typeHandler);
        JdbcType jdbcTypeEnum = resolveJdbcType(jdbcType);
        // 通过上面的属性构建一个 ResultMapping 对象
        return builderAssistant.buildResultMapping(resultType, property, column, javaTypeClass, jdbcTypeEnum, nestedSelect, nestedResultMap, notNullColumn, columnPrefix, typeHandlerClass, flags, resultSet, foreignColumn, lazy);
    }

    private String processNestedResultMappings(XNode context, List<ResultMapping> resultMappings, Class<?> enclosingType) {
        if (Arrays.asList("association", "collection", "case").contains(context.getName())
            && context.getStringAttribute("select") == null) {
          validateCollection(context, enclosingType);
          ResultMap resultMap = resultMapElement(context, resultMappings, enclosingType);
          return resultMap.getId();
        }
        return null;
    }
    //... 省略部分代码
}
----

获取节点的各种属性信息，这里我们可以看到，当节点为 `<association />`，`<collection />`或者 `<case />` 时，则会调用 `processNestedResultMappings` 方法解析成 `ResultMap` 对象，然后返回该对象的 `id`（没有定义会自动生成），这样这个 `RequestMapping` 对象就会关联这个 `ResultMap` 对象了，这个方法内部也是调用 `resultMapElement` 方法生成 `ResultMap` 对象的。

最后通过 `MapperBuilderAssistant` 构造器小助手的 `buildResultMapping` 方法根据这些属性构建一个 `ResultMapping` 对象并返回。

[source,java]
.MapperBuilderAssistant
----
public class MapperBuilderAssistant extends BaseBuilder {
	//... 省略部分代码
    public ResultMapping buildResultMapping(
      Class<?> resultType,
      String property,
      String column,
      Class<?> javaType,
      JdbcType jdbcType,
      String nestedSelect,
      String nestedResultMap,
      String notNullColumn,
      String columnPrefix,
      Class<? extends TypeHandler<?>> typeHandler,
      List<ResultFlag> flags,
      String resultSet,
      String foreignColumn,
      boolean lazy) {
        // <1> 获取属性的 java 类型。例如: java.lang.String。其原理是根据 resultType 通过反射来获取属性类型。
        Class<?> javaTypeClass = resolveResultJavaType(resultType, property, javaType);
        TypeHandler<?> typeHandlerInstance = resolveTypeHandler(javaTypeClass, typeHandler);
        List<ResultMapping> composites;
		// <2> 解析组合字段名称成 ResultMapping 集合，涉及「关联的嵌套查询」
        if ((nestedSelect == null || nestedSelect.isEmpty()) && (foreignColumn == null || foreignColumn.isEmpty())) {
          composites = Collections.emptyList();
        } else {
			// RequestMapping 关联了子查询，如果 column 配置了多个则一一再创建 RequestMapping 对象
          composites = parseCompositeColumnName(column);
        }
        // <3> 创建 ResultMapping 对象
        return new ResultMapping.Builder(configuration, property, column, javaTypeClass)
            .jdbcType(jdbcType)
            .nestedQueryId(applyCurrentNamespace(nestedSelect, true))
            .nestedResultMapId(applyCurrentNamespace(nestedResultMap, true))
            .resultSet(resultSet)
            .typeHandler(typeHandlerInstance)
            .flags(flags == null ? new ArrayList<>() : flags)
            .composites(composites)
            .notNullColumns(parseMultipleColumnNames(notNullColumn))
            .columnPrefix(columnPrefix)
            .foreignColumn(foreignColumn)
            .lazy(lazy)
            .build();
    }
    //... 省略部分代码
}

----

. 解析对应的 Java Type 和 TypeHandler 的 Class 对象，
. 如果嵌套的子查询存在组合字段，则一一解析成 `ResultMapping` 对象，例如需要在返回的结果集中取多个列作为嵌套查询的入参，那么你需要配置多个映射关系。例如子查询的入参对象有两个属性，分别是 `name` 和 `age`，而上一层查询从数据库返回的列名是 `studentName` 和 `studentAge`，那么你需要在嵌套查询配置 `column` 属性为：`{name=studentName,age=studentAge}`，不然没有映射关系无法设置子查询的入参，这样就会为该属性创建两个 `ResultMapping` 添加到 `composites` 集合中
. 调用 `applyCurrentNamespace` 方法，拼接命名空间
. 调用 `parseMultipleColumnNames` 方法，将字符串（以逗号分隔）解析成集合，作用： 默认情况下，在至少一个被映射到属性的列不为空时，子对象才会被创建。
. 通过 `ResultMapping.Builder` 构建一个 `ResultMapping` 对象

`ResultMapping` 对象构建成功后，最后通过 `ResultMapResolver.resolve()` 方法执行解析，


至此整个的 `ResultMap` 对象的解析过程到这里就结束了。内部调用 `MapperBuilderAssistant` 构造器小助手的 `addResultMap` 来生成 `ResultMap` 对象

[source,java]
----
public class XMLMapperBuilder extends BaseBuilder {
	  public ResultMap addResultMap(String id, Class<?> type, String extend, Discriminator discriminator,
            List<ResultMapping> resultMappings, Boolean autoMapping) {
            // <1> 获得 ResultMap 编号，即格式为 `${namespace}.${id}`
            id = applyCurrentNamespace(id, false);
			// <2.1> 获取完整的父 ResultMap 属性，即格式为 `${namespace}.${extend}`。从这里的逻辑来看，貌似只能获取自己 namespace 下的 ResultMap 。
			extend = applyCurrentNamespace(extend, true);
            // <2.2> 如果有父类，则将父类的 ResultMap 集合，添加到 resultMappings 中。
            if (extend != null) {
				// <2.2> 如果有父类，则将父类的 ResultMap 集合，添加到 resultMappings 中。
                if (!configuration.hasResultMap(extend)) {
                    throw new IncompleteElementException("Could not find a parent resultmap with id '" + extend + "'");
                }
                ResultMap resultMap = configuration.getResultMap(extend);
				// 获取 extend 的 ResultMap 对象的 ResultMapping 集合，并移除 resultMappings
                List<ResultMapping> extendedResultMappings = new ArrayList<>(resultMap.getResultMappings());
                extendedResultMappings.removeAll(resultMappings);
                // Remove parent constructor if this resultMap declares a constructor.
                // 判断当前的 resultMappings 是否有构造方法，如果有，则从 extendedResultMappings 移除所有的构造类型的 ResultMapping
                boolean declaresConstructor = false;
                for (ResultMapping resultMapping : resultMappings) {
                    if (resultMapping.getFlags().contains(ResultFlag.CONSTRUCTOR)) {
                        declaresConstructor = true;
                        break;
                    }
                }
                if (declaresConstructor) {
                    extendedResultMappings.removeIf(resultMapping -> resultMapping.getFlags().contains(ResultFlag.CONSTRUCTOR));
                }
				// 将 extendedResultMappings 添加到 resultMappings 中
                resultMappings.addAll(extendedResultMappings);
            }
			// <3> 创建 ResultMap 对象
            ResultMap resultMap = new ResultMap.Builder(configuration, id, type, resultMappings, autoMapping)
                .discriminator(discriminator)
                .build();
			// <4> 添加到 configuration 中
            configuration.addResultMap(resultMap);
            return resultMap;
          }
}
----

. 调用 `applyCurrentNamespace` 方法拼接 `namespace` 与 `id`，获得 `ResultMap` 的唯一编号，格式为 `\$\{namespace\}.\$\{id\}`
. 获得父 `ResultMap` 的唯一编号 extend，格式为 `\$\{namespace\}.\$\{extend\}`
.. extend 为 null 则直接忽略
.. 否则获取对应的 `ResultMap` 对象，则将 `extend` 的 `ResultMapping` 集合和自己的 `ResultMapping` 集合进行合并
. 通过 `ResultMap.Builder` 构建一个 `ResultMap` 对象，并添加到 `Configuration` 全局配置中

=== sqlElement 方法

`sqlElement(List<XNode> list)` 方法用于解析所有的 `<sql />` 节点，内部调用 `sqlElement(List<XNode> list, String requiredDatabaseId)` 方法，代码如下：

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
	//... 省略部分代码
    private void sqlElement(List<XNode> list, String requiredDatabaseId) {
		// <1> 遍历所有 <sql /> 节点
		for (XNode context : list) {
			// <2> 获得 databaseId 属性
			String databaseId = context.getStringAttribute("databaseId");
			// <3> 获得完整的 id 属性
			String id = context.getStringAttribute("id");
			// 设置为 `${namespace}.${id}` 格式
			id = builderAssistant.applyCurrentNamespace(id, false);
			// <4> 判断 databaseId 是否匹配
			if (databaseIdMatchesCurrent(id, databaseId, requiredDatabaseId)) {
				// <5> 添加到 sqlFragments 中
				sqlFragments.put(id, context);
			}
		}
	}
	//... 省略部分代码
}
----

这里仅仅是将该 `<sql />` 节点保存至 `Map<String, XNode> sqlFragments` 对象中（该对象保存与 Configuration 全局配置对象中），后续解析其他 SQL 语句中会使用到，例如查询语句中使用了 `<include />` 标签，则需要获取到对应的 `<sql />` 节点将其替换。

=== buildStatementFromContext 方法

`buildStatementFromContext(List<XNode> list)` 方法用于解析 `<select />` `<insert />` `<update />` `<delete />` 节点

内部调用 `buildStatementFromContext(List<XNode> list, String requiredDatabaseId)` 方法逐个解析生成 `MappedStatement` 对象，代码如下：

[source,java]
.XMLMapperBuilder
----
public class XMLMapperBuilder extends BaseBuilder {
	//... 省略部分代码
    private void buildStatementFromContext(List<XNode> list, String requiredDatabaseId) {
		// <1> 遍历 <select /> <insert /> <update /> <delete /> 节点
		for (XNode context : list) {
			// <1> 创建 XMLStatementBuilder 对象
			final XMLStatementBuilder statementParser = new XMLStatementBuilder(configuration, builderAssistant, context, requiredDatabaseId);
			try {
				// 解析成 MappedStatement 对象
				statementParser.parseStatementNode();
			} catch (IncompleteElementException e) {
				// <2> 解析失败，添加到 configuration 中
				configuration.addIncompleteStatement(statementParser);
			}
		}
	}
	//... 省略部分代码
}
----

为该节点创建 `XMLStatementBuilder` 对象，然后调用其 `parseStatementNode()` 解析成 `MappedStatement` 对象，解析过程在下面的 `XMLStatementBuilder` 中讲到

[source,java]
.XMLStatementBuilder
----
public class XMLStatementBuilder extends BaseBuilder {
	//... 省略部分代码
    public void parseStatementNode() {
		// 获得 id 属性，编号。
        String id = context.getStringAttribute("id");
		// 获得 databaseId ， 判断 databaseId 是否匹配
        String databaseId = context.getStringAttribute("databaseId");

        if (!databaseIdMatchesCurrent(id, databaseId, this.requiredDatabaseId)) {
          return;
        }
        // 获取该节点名称
        String nodeName = context.getNode().getNodeName();
		// <1> 根据节点名称判断 SQL 类型
        SqlCommandType sqlCommandType = SqlCommandType.valueOf(nodeName.toUpperCase(Locale.ENGLISH));
		// 是否为 Select 语句
        boolean isSelect = sqlCommandType == SqlCommandType.SELECT;
		// <2> 是否清空缓存
        boolean flushCache = context.getBooleanAttribute("flushCache", !isSelect);
		// <3> 是否使用缓存
        boolean useCache = context.getBooleanAttribute("useCache", isSelect);
        boolean resultOrdered = context.getBooleanAttribute("resultOrdered", false);

        // Include Fragments before parsing
        XMLIncludeTransformer includeParser = new XMLIncludeTransformer(configuration, builderAssistant);
		// <4> 将该节点的子节点 <include /> 转换成 <sql /> 节点
        includeParser.applyIncludes(context.getNode());

		// 获取参数类型名称
        String parameterType = context.getStringAttribute("parameterType");
		// <5> 参数类型名称转换成 Java Type
        Class<?> parameterTypeClass = resolveClass(parameterType);

		// <6> 获得 lang 对应的 LanguageDriver 对象
        String lang = context.getStringAttribute("lang");
        LanguageDriver langDriver = getLanguageDriver(lang);

        // Parse selectKey after includes and remove them.
        // <7> 将该节点的子节点 <selectKey /> 解析成 SelectKeyGenerator 生成器
        processSelectKeyNodes(id, parameterTypeClass, langDriver);

        // Parse the SQL (pre: <selectKey> and <include> were parsed and removed)
        KeyGenerator keyGenerator;
        String keyStatementId = id + SelectKeyGenerator.SELECT_KEY_SUFFIX;
        keyStatementId = builderAssistant.applyCurrentNamespace(keyStatementId, true);

        /*
         * <8>
         * 1. 如果上面存在 <selectKey /> 子节点，则获取上面对其解析后生成的 SelectKeyGenerator
         * 2. 否则判断该节点是否配置了 useGeneratedKeys 属性为 true 并且是 插入语句，则使用 Jdbc3KeyGenerator
         */
        if (configuration.hasKeyGenerator(keyStatementId)) {
            keyGenerator = configuration.getKeyGenerator(keyStatementId);
        } else {
              keyGenerator = context.getBooleanAttribute("useGeneratedKeys",
                  configuration.isUseGeneratedKeys() && SqlCommandType.INSERT.equals(sqlCommandType))
                  ? Jdbc3KeyGenerator.INSTANCE : NoKeyGenerator.INSTANCE;
        }

		// <9> 创建对应的 SqlSource 对象，保存了该节点下 SQL 相关信息
        SqlSource sqlSource = langDriver.createSqlSource(configuration, context, parameterTypeClass);
		// <10> 获得 Statement 类型，默认 PREPARED
        StatementType statementType = StatementType.valueOf(context.getStringAttribute("statementType", StatementType.PREPARED.toString()));
        Integer fetchSize = context.getIntAttribute("fetchSize");
        Integer timeout = context.getIntAttribute("timeout");
        String parameterMap = context.getStringAttribute("parameterMap");
		// <11> 获得返回结果类型名称
        String resultType = context.getStringAttribute("resultType");
		// 获取返回结果的 Java Type
        Class<?> resultTypeClass = resolveClass(resultType);
		// 获取 resultMap
        String resultMap = context.getStringAttribute("resultMap");
        String resultSetType = context.getStringAttribute("resultSetType");
        ResultSetType resultSetTypeEnum = resolveResultSetType(resultSetType);
        if (resultSetTypeEnum == null) {
            resultSetTypeEnum = configuration.getDefaultResultSetType();
        }
		// 对应的 java 属性，结合 useGeneratedKeys 使用
        String keyProperty = context.getStringAttribute("keyProperty");
		// 对应的 column 列名，结合 useGeneratedKeys 使用
        String keyColumn = context.getStringAttribute("keyColumn");
        String resultSets = context.getStringAttribute("resultSets");

		// <12> 构建 MappedStatement 对象
        builderAssistant.addMappedStatement(id, sqlSource, statementType, sqlCommandType,
            fetchSize, timeout, parameterMap, parameterTypeClass, resultMap, resultTypeClass,
            resultSetTypeEnum, flushCache, useCache, resultOrdered,
            keyGenerator, keyProperty, keyColumn, databaseId, langDriver, resultSets);
    }

	//... 省略部分代码
}
----

这部分的解析比较长，也比较繁琐。

. 根据节点名称设置 SQL 语句类型，SqlCommandType 有六种类型：`UNKNOWN`, `INSERT`, `UPDATE`, `DELETE`, `SELECT`, `FLUSH`
. 获取 `flushCache` 属性，是否清空缓存，非查询语句默认都是 `true`
. 获取 `useCache` 属性，是否开启缓存，查询语句默认为 `true`
. 创建 `XMLIncludeTransformer` 对象，调用其 `applyIncludes` 方法将 `<include />` 转换成 `<sql />` 节点，大致逻辑就是从 sqlFragments（前面已经将所有的 `<sql />` 节点进行解析存放在其中了）获取对应的 `<sql />` 节点，然后替换 `<include />` 节点，具体的转换过程这里就不讲述了，没有特别复杂。
. 获取 `parameterType` 属性，参数类型，转换成 `Class` 对象
. 获取 lang 属性，`LanguageDriver` 语言驱动器，默认为 `XMLLanguageDriver`
. 将该节点的 `<selectKey />` 子节点解析成 `SelectKeyGenerator` 生成器，用于生成一个 key 设置到返回对象中，在 `processSelectKeyNodes` 方法中可以看到，该过程也会生成一个 `MappedStatement` 对象，生成的对象的 `id` 为 `statementId+'!selectKey'`
. 解析 `useGeneratedKeys` 属性，获取 `SelectKeyGenerator` 生成器，如果第 7 步没有生成才会进入这里，直接返回 `Jdbc3KeyGenerator` 单例
. 根据 `XMLLanguageDriver` 语言驱动创建 `SqlSource` 对象，通过这个对象可以获取到对应的 SQL 语句，在后面的 <<init-sql.adoc#mybatis-init-sql>> 分析该创建过程
. 获取 `statementType` 属性，`Statement` 类型，默认 `PREPARED`
. 获取其他的一下相关信息，例如：`timeout`、`resultMap`、`keyProperty`、`keyColumn` 等属性，其中配置的 `resultType` 也会转换成 `ResultMap` 对象
. 通过 `MapperBuilderAssistant` 构造器小助手根据这些属性信息构建一个 `MappedStatement` 对象

[source,java]
.MapperBuilderAssistant
----
public class MapperBuilderAssistant extends BaseBuilder {
	//... 省略部分代码
    public MappedStatement addMappedStatement(String id, SqlSource sqlSource, StatementType statementType,
            SqlCommandType sqlCommandType, Integer fetchSize, Integer timeout, String parameterMap,
            Class<?> parameterType, String resultMap, Class<?> resultType, ResultSetType resultSetType,
            boolean flushCache, boolean useCache, boolean resultOrdered, KeyGenerator keyGenerator, String keyProperty,
            String keyColumn, String databaseId, LanguageDriver lang, String resultSets) {

        // <1> 如果的指向的 Cache 未解析，抛出异常
        if (unresolvedCacheRef) {
            throw new IncompleteElementException("Cache-ref not yet resolved");
        }

        // <2> 获得 id 编号，格式为 `${namespace}.${id}`
        id = applyCurrentNamespace(id, false);
        // 是否为查询语句
        boolean isSelect = sqlCommandType == SqlCommandType.SELECT;

        // <3> 创建 MappedStatement.Builder 对象
        MappedStatement.Builder statementBuilder = new MappedStatement.Builder(configuration, id, sqlSource,
                sqlCommandType).resource(resource).fetchSize(fetchSize).timeout(timeout).statementType(statementType)
                        .keyGenerator(keyGenerator).keyProperty(keyProperty).keyColumn(keyColumn).databaseId(databaseId)
                        .lang(lang).resultOrdered(resultOrdered).resultSets(resultSets)
                        .resultMaps(getStatementResultMaps(resultMap, resultType, id)).resultSetType(resultSetType)
                        .flushCacheRequired(valueOrDefault(flushCache, !isSelect))
                        .useCache(valueOrDefault(useCache, isSelect)).cache(currentCache);

        // <4> 生成 ParameterMap 对象
        ParameterMap statementParameterMap = getStatementParameterMap(parameterMap, parameterType, id);
        if (statementParameterMap != null) {
            statementBuilder.parameterMap(statementParameterMap);
        }

        // <5> 创建 MappedStatement 对象
        MappedStatement statement = statementBuilder.build();
        // <6> 添加到 configuration 中
        configuration.addMappedStatement(statement);
        return statement;
    }
	//... 省略部分代码
}
----

. 如果的指向的 Cache 未解析，抛出异常
. 获得 `MappedStatement` 的唯一编号 id，格式为 `\$\{namespace\}.\$\{id\}`
. 创建 `MappedStatement.Builder` 对象
. 创建 `ParameterMap` 对象，进入 `getStatementParameterMap` 方法可以看到，`ParameterMap的Class<?> type` 属性设置为入参类型，String id 设置为 `statementId`
`<parameterMap />` 标签已经被废弃，所以这里不会配置 `parameterMap` 属性
. 通过 `MappedStatement.Builder` 构建一个 `MappedStatement` 对象，并添加到 Configuration 全局配置中

=== 总结

解析 `XML` 映射文件的过程中是在 `XMLMapperBuilder` 中进行的，会使用到 `MapperBuilderAssistant` 小助手用于创建 `ResultMapping`、`ResultMap` 和 `MappedStatement` 对象

其中解析 `<select />`， `<update />`， `<delete />`， `<insert />` 标签的解析过程又在 `XMLStatementBuilder` 对象中进行

最终所有的 MyBatis 配置、Mapper 接口和 XML 映射文件生成的相应对象都保存在了 Configuration 全局配置对象中，那么接下来我们来看看 SQL 语句在 MyBatis 中是如何初始化的