[[mybatis-init-sql]]
== SQL 初始化

我们以下面一个为演示

[source,xml]
.UserMapper.xml
----
<select id="getUser" resultMap="userResultMap">
    select * from saga_user
    <where>
        <if test="id != null">
            id = #{param1}
        </if>
    </where>
</select>
----

其对应的 Mapper 对象为

[source,java]
.UserMapper
----
public interface UserMapper extends BaseMapper<User> {

    /**
     * 获取用户.
     * @return 用户对象
     */
    User getUser(Long id);

}
----

然后，我们让应用程序启动之后，执行这个方法，我们来看看其内部发生了什么

[source,java]
.MybatisSQLParseApplication
----
@SpringBootApplication
@MapperScan("com.mybatis.sql.**.mapper.**")
public class MybatisSQLParseApplication {

	public static void main(String[] args) {
		SpringApplication.run(MybatisSQLParseApplication.class,args);
	}

	@Bean
	public CommandLineRunner runner(UserMapper mapper) {
		return args -> {
			User user = mapper.getUser(1L);
			System.out.println(user);
		};
	}
}

----

在上一节中，我们提到了 Mybatis 如何解析 `<select />` `<insert />` `<update />` `<delete />` 节点中，会创建一个 `SqlSource` 对象，实现动态 SQL 语句。那我们来看看它是如何创建  `SqlSource` 对象的。让我们从下面这一段代码开始

=== 获取 `SqlSource` 对象

我们从 `XMLStatementBuilder.parseStatementNode()` 方法开始

[source,java]
.XMLStatementBuilder.parseStatementNode()
----
public class XMLStatementBuilder extends BaseBuilder {
	//... 省略部分代码
    public void parseStatementNode() {
		//... 省略部分代码
        // 创建对应的 SqlSource 对象，保存了该节点下 SQL 相关信息
        SqlSource sqlSource = langDriver.createSqlSource(configuration, context, parameterTypeClass);
		//... 省略部分代码
    }
	//... 省略部分代码
}
----

[source,java]
.XMLLanguageDriver
----
public class XMLLanguageDriver implements LanguageDriver {
	//... 省略部分代码
    @Override
    public SqlSource createSqlSource(Configuration configuration, XNode script, Class<?> parameterType) {
        XMLScriptBuilder builder = new XMLScriptBuilder(configuration, script, parameterType);
        return builder.parseScriptNode();
    }
    //... 省略部分代码
}

----

. `langDriver` 是从 Configuration 全局配置对象中获取的默认实现类，对应的也就是 `XMLLanguageDriver`，在 Configuration 初始化的时候设置的。
. 创建 `XMLScriptBuilder` 对象，解析脚本，返回 `SqlSource` 对象。

[source,java]
.XMLScriptBuilder
----
public class XMLScriptBuilder extends BaseBuilder {
    //... 省略部分代码
	public SqlSource parseScriptNode() {
		// 解析 XML 或者注解中定义的 SQL
        MixedSqlNode rootSqlNode = parseDynamicTags(context);
        SqlSource sqlSource;
        if (isDynamic) {
			// 解析 XML 或者注解中定义的 SQL
            sqlSource = new DynamicSqlSource(configuration, rootSqlNode);
        } else {
            sqlSource = new RawSqlSource(configuration, rootSqlNode, parameterType);
        }
        return sqlSource;
    //... 省略部分代码
    }
}

----

. 通过调用 `parseDynamicTags(XNode node)` 方法，将解析 SQL 成 `MixedSqlNode` 对象，主要是将一整个 SQL 解析成一系列的 `SqlNode` 对象
. 如果是动态 SQL 语句，使用了 MyBatis 自定义的 XML 标签（`<if />` 等）或者使用了 `${}`，则封装成 `DynamicSqlSource` 对象
. 否则就是静态 SQL 语句，封装成 `RawSqlSource` 对象，`RawSqlSource` 对象在构造时会通过 `getSql` 方法直接获取到他的 sql 语句，这里不做过多解析，您可以查看相关源码进行了解

`parseDynamicTags(XNode node)` 方法将 SQL 脚本（XML 或者注解中定义的 SQL ）解析成 `MixedSqlNode` 对象，代码如下：

[source,java]
.XMLScriptBuilder
----
public class XMLScriptBuilder extends BaseBuilder {
    //... 省略部分代码
    private void initNodeHandlerMap() {
        nodeHandlerMap.put("trim", new TrimHandler());
        nodeHandlerMap.put("where", new WhereHandler());
        nodeHandlerMap.put("set", new SetHandler());
        nodeHandlerMap.put("foreach", new ForEachHandler());
        nodeHandlerMap.put("if", new IfHandler());
        nodeHandlerMap.put("choose", new ChooseHandler());
        nodeHandlerMap.put("when", new IfHandler());
        nodeHandlerMap.put("otherwise", new OtherwiseHandler());
        nodeHandlerMap.put("bind", new BindHandler());
    }

    protected MixedSqlNode parseDynamicTags(XNode node) {
		/*
         * <1> 创建 SqlNode 数组
         */
        List<SqlNode> contents = new ArrayList<>();
        /*
         * <2> 遍历 SQL 节点中所有子节点
         * 这里会对该节点内的所有内容进行处理然后返回 NodeList 对象
         * 1. 文本内容会被解析成 '<#text></#text>' 节点，就算一个换行符也会解析成这个
         * 2. <![CDATA[ content ]]> 会被解析成 '<#cdata-section>content</#cdata-section>' 节点
         * 3. 其他动态<if /> <where />
         */
        NodeList children = node.getNode().getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            /*
             * 当前子节点
             * i = 0 时：child 为
             * <#text>
             *      select * from saga_user
             * 		</#text>
             * i = 1 时：child 为
             * <where>
             *    <if test="id != null">
             *				id = #{param1}
             *	  </if>
             * </where>
             */
            XNode child = node.newXNode(children.item(i));
            // <2.1> 如果类型是 Node.CDATA_SECTION_NODE 或者 Node.TEXT_NODE 时
            if (child.getNode().getNodeType() == Node.CDATA_SECTION_NODE // <![CDATA[ ]]>节点
                    || child.getNode().getNodeType() == Node.TEXT_NODE) { // 纯文本
                // <2.1.1> 获得内容
                String data = child.getStringBody("");
                // <2.1.2> 创建 TextSqlNode 对象
                TextSqlNode textSqlNode = new TextSqlNode(data);
				// <2.1.2.1> 如果是动态的 TextSqlNode 对象，也就是使用了 '${}'
                if (textSqlNode.isDynamic()) {
                    // 添加到 contents 中
                    contents.add(textSqlNode);
                    // 标记为动态 SQL
                    isDynamic = true;
                } else {
					// <2.1.2.2> 如果是非动态的 TextSqlNode 对象，没有使用 '${}'
                    // <2.1.2> 创建 StaticTextSqlNode 添加到 contents 中
                    contents.add(new StaticTextSqlNode(data));
                }
            } else if (child.getNode().getNodeType() == Node.ELEMENT_NODE) {
				// issue #628 <2.2> 如果类型是 Node.ELEMENT_NODE
                // <2.2.1> 根据子节点的标签，获得对应的 NodeHandler 对象
                String nodeName = child.getNode().getNodeName();
				// nodeHandlerMap 在构造时已经进行了初始化并添加了默认 9 个，请看上一段代码
                // 当为 where 子句时，此时的 handler 为 where -> WhereHandler
                NodeHandler handler = nodeHandlerMap.get(nodeName);
                if (handler == null) {
					// 获得不到，说明是未知的标签，抛出 BuilderException 异常
                    throw new BuilderException("Unknown element <" + nodeName + "> in SQL statement.");
                }
                // <2.2.2> 执行 NodeHandler 处理,
                handler.handleNode(child, contents);
                // <2.2.3> 标记为动态 SQL
                isDynamic = true;
            }
        }
        // <3> 创建 MixedSqlNode 对象 XMLScriptBuilder 对象
        return new MixedSqlNode(contents);
    }
    //... 省略部分代码
}

----

. 创建 SqlNode 数组 contents，用于保存解析 SQL 后的一些列 SqlNode 对象
. 获取定义的 SQL 节点中所有子节点，返回一个 NodeList 对象，这个对象中包含了该 SQL 节点内的所有信息，然后逐个遍历子节点
.. 如果子节点是 `<#text />` 或者 `<#cdata-section />` 类型
... 获取子节点的文本内容
... 创建 `TextSqlNode` 对象
.... 调用 TextSqlNode 的 `isDynamic()` 方法，点击去该进去看看就知道了，如果文本中使用了 `${}`，则标记为动态 SQL 语句，将其添加至 contents 数组中
.... 否则就是静态文本内容，创建对应的 `StaticTextSqlNode` 对象，将其添加至 contents 数组中
.. 如果类型是 Node.ELEMENT_NODE 时，也就是 MyBatis 的自定义标签
... 根据子节点的标签名称，获得对应的 NodeHandler 对象,
... 执行 NodeHandler 的 `handleNode` 方法处理该节点，创建不同类型的 `SqlNode` 并添加到 contents 数组中，如何处理的在下面讲述
... 标记为动态 SQL 语句
. 最后将创建 contents 封装成 `MixedSqlNode` 对象

在 `handler.handleNode(child, contents)` 处理节点时，我们这里不对每一个标签进行说明，其原理大致一样。我们这里仅以以下标签为例：

[source,xml]
----
<where>
    <if test="id != null">
        id = #{param1}
    </if>
</where>
----

这时，handler 对应的类型应该为 `WhereHandler`，执行 `WhereHandler.handleNode(child, contents)` 方法，让我们继续追踪这一段代码。

[source,java]
.XMLScriptBuilder
----
public class XMLScriptBuilder extends BaseBuilder {
    //... 省略部分代码
    @Override
    public void handleNode(XNode nodeToHandle, List<SqlNode> targetContents) {
		// 继续执行 parseDynamicTags 方法。
        MixedSqlNode mixedSqlNode = parseDynamicTags(nodeToHandle);
        WhereSqlNode where = new WhereSqlNode(configuration, mixedSqlNode);
        targetContents.add(where);
    }
    //... 省略部分代码
}

----

继续执行 `parseDynamicTags` 方法，`where` 的子标签为 `if`，所以此时的 handler 为 `IfHandler`。 执行 `IfHandler.handleNode(child, contents)` 方法。

[source,java]
.XMLScriptBuilder
----
public class XMLScriptBuilder extends BaseBuilder {
    //... 省略部分代码
    @Override
    public void handleNode(XNode nodeToHandle, List<SqlNode> targetContents) {
		// 获取到的 MixedSqlNode 包含一个 content 内容为 `id = #{param1}`
        MixedSqlNode mixedSqlNode = parseDynamicTags(nodeToHandle);
		// 获取到的 test 内容为 `id != null`
        String test = nodeToHandle.getStringAttribute("test");
        IfSqlNode ifSqlNode = new IfSqlNode(mixedSqlNode, test);
        targetContents.add(ifSqlNode);
    }
    //... 省略部分代码
}

----

又重复执行 `parseDynamicTags` 方法，由于 if 下面已经没有子标签了，所有不会再进入 `parseDynamicTags` 方法了，方法一步步返回，让我们再回头看 `parseScriptNode` 方法的最终返回值 `rootSqlNode` 的结构：

[source,text]
----
MixedSqlNode(rootSqlNode)
    contents(3个节点)
        StaticTextSqlNode
            content: select * from saga_user
        WhereSqlNode
            contents(3 个节点)
                StaticTextSqlNode：
                IfSqlNode
                    test: id != null
                    content(1 个节点)
                        MixedSqlNode
                            contents(1 个节点)
                                StaticTextSqlNode
                                    content: id = #{param1}
                StaticTextSqlNode：
        StaticTextSqlNode：
----

然后根据 `isDynamic` 创建 `SqlSource` 对象。然后将 `SqlSource` 对象添加到 `MappedStatement` 中， 至此，SqlSource 对象创建完成。

=== 总结

在 Mybatis 中，实现动态 SQL 的原理如下：

. 通过 Xml 文件配置 Mapper 对应的 SQL 语句，这些 SQL 语句中可以包含动态 SQL 语句。
. Mybatis 会在运行时将 Xml 文件中的 SQL 语句解析成 `SqlNode` 的树形结构，该结构中的每个 `SqlNode` 对象表示 Xml 文件中的一个节点，每个 `SqlNode` 都会实现 `SqlNode` 接口。
. 动态 SQL 语句的生成是通过 `SqlNode` 接口的实现类的实现完成的，具体生成逻辑定义在 `SqlNode` 的实现类中。
. 当 Mybatis 执行 Mapper 中的方法时，会使用 `SqlSource` 类的 `getBoundSql` 方法生成最终的动态 SQL 语句，该方法会对 `SqlNode` 的树形结构进行遍历， 并利用 `XMLScriptBuilder.NodeHandler` 的多个实现类动态生成最终的 SQL 语句。关于 SQL 执行的细节，请查看 <<sql-parse.adoc#mybatis-init-excute>>

因此，动态 SQL 的生成是通过对 `SqlNode` 接口的实现类的利用和遍历实现的，Mybatis 在运行时通过组合 `SqlNode` 和通过遍历 `SqlNode` 生成的结果来生成最终的动态 SQL 语句。