# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Jcohy-Study CI with Gradle

on:
  push:
    branches:
    - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置 JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 为 gradlew 赋予执行权限
        run: chmod +x gradlew
      - name: 上传到 OSS
        if: ${{ github.event.inputs.uploadOss == 'true'}}
        run: ./gradlew uploadOssFiles -x asciidoctorPdf
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
